// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjAQ-GPphQqGZlQ9yxkCvjYqLDtAtknxU',
    appId: '1:1024414693257:web:2bab4168af1c20deb21358',
    messagingSenderId: '1024414693257',
    projectId: 'fir-flutter-2bf4a',
    authDomain: 'fir-flutter-2bf4a.firebaseapp.com',
    storageBucket: 'fir-flutter-2bf4a.firebasestorage.app',
    measurementId: 'G-KD3KW8KVJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp_SVRO-pLcXhVVRFmA7oiWWBBXxmejV0',
    appId: '1:1024414693257:android:9c75bb3852da91e4b21358',
    messagingSenderId: '1024414693257',
    projectId: 'fir-flutter-2bf4a',
    storageBucket: 'fir-flutter-2bf4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJ8QTCkK8FVRDIE62CQyUTwqPZnv159Q',
    appId: '1:1024414693257:ios:3311afb17e2c1d8cb21358',
    messagingSenderId: '1024414693257',
    projectId: 'fir-flutter-2bf4a',
    storageBucket: 'fir-flutter-2bf4a.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJ8QTCkK8FVRDIE62CQyUTwqPZnv159Q',
    appId: '1:1024414693257:ios:3311afb17e2c1d8cb21358',
    messagingSenderId: '1024414693257',
    projectId: 'fir-flutter-2bf4a',
    storageBucket: 'fir-flutter-2bf4a.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjAQ-GPphQqGZlQ9yxkCvjYqLDtAtknxU',
    appId: '1:1024414693257:web:f34e0df10ee7addeb21358',
    messagingSenderId: '1024414693257',
    projectId: 'fir-flutter-2bf4a',
    authDomain: 'fir-flutter-2bf4a.firebaseapp.com',
    storageBucket: 'fir-flutter-2bf4a.firebasestorage.app',
    measurementId: 'G-XNDNE4CT7J',
  );
}
